version: "1"

steps:
  - name: publish strapi
    image: target/vela-kaniko:v0.14.0
    pull: always
    # secrets: [ docker_username, docker_password ]
    ruleset:
      event: push
      branch: main
    parameters:
      file: Dockerfile.prod
      registry: index.docker.io
      repo: index.docker.io/noahspan/strapi
      tags:
        - latest
      log_level: trace
      username: noahspan
      password: SmFtZXNuMTIkCg==

secrets:
  - name: docker_username
    key: noahspannbauer/docker_username
    engine: native
    type: org
  - name: docker_password
    key: noahspannbauer/docker_password
    engine: native
    type: org